//============================================================================
/// @file calculator.idl
///
                                                           //qidl copyright
//% Copyright (c) 2012-2014 Qualcomm Technologies, Inc.
                                                           //qidl nested=false
//% All Rights Reserved.
//% Qualcomm Confidential and Proprietary
//============================================================================

#include "AEEStdDef.idl"

interface calculator {
   long sum(in sequence<long> vec, rout long long res);
   //long diff(in sequence<long> vec, rout long long res);
};

